const state={structure:null,thing:null,numerative:null,size:null,colour:[],relationship:null,arrangement:null,configuration:null,surface:[],symptoms:[],exam:[]};
const structure={flat:{label:'Flat',things:['macule','patch']},raised_solid:{label:'Raised & solid',things:['papule','plaque','nodule']},fluid_filled:{label:'Fluid-filled',things:['vesicle','bulla']},purulent:{label:'Purulent',things:['pustule']},transient_edematous:{label:'Transient & puffy',things:['wheal']}};
const options={numerative:['Solitary','Few','Multiple','Numerous'],size:['1 mm','2 mm','3 mm','5 mm','0.5 cm','1 cm','2 cm','3 cm','4 cm'],colour:['erythematous','violaceous','hyperpigmented','hypopigmented','skin-colored','purpuric'],relationship:['discrete','confluent'],arrangement:['scattered','grouped','linear','dermatomal'],configuration:['annular','targetoid','reticulated','serpiginous'],surface:['smooth','scaly','crusted','excoriated','eroded','ulcerated','lichenified','weeping'],symptoms:['pruritic','painful','burning','asymptomatic'],exam:['tender to palpation','warm','indurated','fluctuant','mobile','fixed','expresses purulent material','expresses keratinous material']};
const meta={structure:'ENTRY CONDITION (structure)',thing:'THING (computed)',numerative:'NUMERATIVE',size:'QUANTIFIER (size)',colour:'EPITHET (colour)',relationship:'CLASSIFIER (relationship)',arrangement:'CLASSIFIER (arrangement)',configuration:'CLASSIFIER (configuration)',surface:'CLASSIFIER (surface)',symptoms:'PATIENT REPORT',exam:'EXAM FINDING'};
const multi={colour:2,surface:3,symptoms:3,exam:4};
const flow=document.querySelector('#workflow');
function btn(text,selected,disabled,fn,extra=''){const b=document.createElement('button');b.type='button';b.className=`choice ${selected?'selected':''} ${extra}`;b.textContent=text;b.disabled=disabled;b.setAttribute('aria-pressed',String(selected));b.onclick=fn;return b}
function station(title,key,note,gated=false){const s=document.createElement('section');s.className='system';s.id='station-'+key;s.innerHTML=`<div class="system-head"><h2>${title}</h2><small>${gated?'gated / computed':'optional unless indicated'}</small></div><div class="machine ${gated?'gated':''}"><div class="options"></div><p class="hint">${note}</p></div>`;flow.append(s);return s.querySelector('.options')}
function single(box,key,vals,disabled=false){box.append(btn('UNREALIZED',state[key]===null,false,()=>{state[key]=null;if(key==='numerative')state.arrangement=null;render()},'empty'));vals.forEach(v=>box.append(btn(v,state[key]===v,disabled,()=>{state[key]=v;render()})))}
function toggles(box,key,vals){box.append(btn('CLEAR / UNREALIZED',!state[key].length,false,()=>{state[key]=[];render()},'empty'));vals.forEach(v=>{let disabled=false;if(key==='surface'){if(v==='smooth')disabled=state.surface.some(x=>x!=='smooth');else disabled=state.surface.includes('smooth')}if(key==='symptoms'){if(v==='asymptomatic')disabled=state.symptoms.some(x=>x!=='asymptomatic');else disabled=state.symptoms.includes('asymptomatic')}if(key==='exam'){if(v==='mobile')disabled=state.exam.includes('fixed');if(v==='fixed')disabled=state.exam.includes('mobile')}box.append(btn(v,state[key].includes(v),disabled,()=>toggle(key,v)))})}
function toggle(key,v){let a=[...state[key]];if(a.includes(v))a=a.filter(x=>x!==v);else{if(a.length>=multi[key]){document.querySelector('#status').textContent=`Interlock: ${meta[key]} permits up to ${multi[key]} selections.`;return}a.push(v)}if(key==='surface'){if(v==='smooth')a=['smooth'];else a=a.filter(x=>x!=='smooth')}if(key==='symptoms'){if(v==='asymptomatic')a=['asymptomatic'];else a=a.filter(x=>x!=='asymptomatic')}if(key==='exam'&&v==='mobile')a=a.filter(x=>x!=='fixed');if(key==='exam'&&v==='fixed')a=a.filter(x=>x!=='mobile');state[key]=a;render()}
function renderStations(){flow.innerHTML='';let b=station('1. Primary structure — entry condition','structure','This choice stays silent in the chart phrase. It engages a compatible lesion-class pathway.');Object.entries(structure).forEach(([id,x])=>b.append(btn(x.label,state.structure===id,false,()=>{state.structure=id;if(!x.things.includes(state.thing))state.thing=x.things[0];if(state.numerative==='Solitary')state.arrangement=null;render()})));
const allowed=state.structure?structure[state.structure].things:[];b=station('2. Thing — primary lesion class','thing',state.structure?`Pathway engaged: ${structure[state.structure].label}. These are the permitted head nouns.`:'Locked until a primary structural pathway is selected.',true);if(!allowed.length)b.append(btn('AWAITING PATHWAY',false,true,()=>{}));else allowed.forEach(v=>b.append(btn(v,state.thing===v,false,()=>{state.thing=v;render()})));
b=station('3. Numerative — how many','numerative','Select one, or keep this lexical system unrealized.');single(b,'numerative',options.numerative);
b=station('4. Quantifier — size','size','Measurement informs morphology, but prompts reflection rather than automatic relabeling.');single(b,'size',options.size);
b=station('5. Epithet — colour','colour','Add up to two compatible colour terms, or leave the system unrealized.');toggles(b,'colour',options.colour);
b=station('6a. Classifier — relationship','relationship','Discrete and confluent are alternatives.');single(b,'relationship',options.relationship);
const arrLocked=state.numerative==='Solitary';b=station('6b. Classifier — arrangement','arrangement',arrLocked?'Array mechanism locked: these descriptors presuppose multiple lesions.':'Choose an arrangement descriptor, or leave it unrealized.');single(b,'arrangement',options.arrangement,arrLocked);
b=station('6c. Classifier — configuration','configuration','A separate shape/configuration system.');single(b,'configuration',options.configuration);
b=station('7. Classifier — surface change','surface','Select up to three. Smooth is an interlock and cannot coexist with a secondary change.');toggles(b,'surface',options.surface);
b=station('8a. Patient report','symptoms','Patient report and examination findings are separate systems.');toggles(b,'symptoms',options.symptoms);
b=station('8b. Examination','exam','Painful and tender to palpation may coexist. Mobile and fixed cannot.');toggles(b,'exam',options.exam)}
function words(a){if(!a.length)return'';if(a.length===1)return a[0];if(a.length===2)return a.join(' and ');return a.slice(0,-1).join(', ')+', and '+a.at(-1)}
function phrase(){if(!state.structure||!state.thing)return'Engage primary structure to begin.';let pre=[];if(state.numerative)pre.push(state.numerative.toLowerCase());if(state.size)pre.push(state.size.replace(' ','-'));pre.push(...state.colour);[state.relationship,state.arrangement,state.configuration].filter(Boolean).forEach(x=>pre.push(x));let p=(pre.join(' ')+(pre.length?' ':'')+state.thing);if(state.numerative&&state.numerative!=='Solitary')p+='s';let surface=state.surface.filter(x=>x!=='smooth');if(surface.length)p+=' with '+words(surface);let q=[...state.symptoms,...state.exam];if(q.length)p+='; '+words(q);return p[0].toUpperCase()+p.slice(1)+'.'}
function renderReadout(){let values={structure:state.structure?structure[state.structure].label+' (silent)':null,thing:state.thing,numerative:state.numerative,size:state.size,colour:state.colour,relationship:state.relationship,arrangement:state.arrangement,configuration:state.configuration,surface:state.surface,symptoms:state.symptoms,exam:state.exam};let r=document.querySelector('#readout');r.innerHTML='';Object.entries(meta).forEach(([k,label])=>{const v=values[k],real=Array.isArray(v)?v.length:!!v,row=document.createElement('div');row.className='readout-row';row.innerHTML=`<span>${label}</span>`;let b=document.createElement('button');b.className='slot '+(real?'':'unrealized');b.textContent=real?(Array.isArray(v)?words(v):v):'undefined · UNREALIZED';if(!real){b.title='Visit this unrealized system';b.onclick=()=>document.querySelector('#station-'+k)?.scrollIntoView({behavior:'smooth',block:'center'})}row.append(b);r.append(row)})}
function render(){if(state.numerative==='Solitary')state.arrangement=null;renderStations();document.querySelector('#chart').textContent=phrase();renderReadout();let optional=['numerative','size','colour','relationship','arrangement','configuration','surface','symptoms','exam'];let n=optional.filter(k=>Array.isArray(state[k])?!state[k].length:!state[k]).length;document.querySelector('#feedback').textContent=state.structure?`${n} lexical system${n===1?'':'s'} remain unrealized. Consider whether each is clinically relevant, not assessed, or intentionally omitted.`:'';document.querySelector('#status').textContent=state.structure?`Structural pathway engaged: ${structure[state.structure].label}. Permitted lesion classes: ${structure[state.structure].things.join(', ')}.`:'Awaiting structural pathway.';let c=Object.values(state).filter(v=>Array.isArray(v)?v.length:!!v).length;document.querySelector('#progress').textContent=`${c} / 8 systems realized`}
const arts=[['🍩','FIG. 1 — reference image. Diagnostic correlation not guaranteed.'],['⚙️','FIG. 2 — gear specimen. Diagnostic correlation not guaranteed.'],['🫐','FIG. 3 — blue reference object. Diagnostic correlation not guaranteed.'],['🫧','FIG. 4 — fluid-filled reference object. Diagnostic correlation not guaranteed.'],['🍇','FIG. 5 — grouped reference object. Diagnostic correlation not guaranteed.'],['🧇','FIG. 6 — reticulated reference object. Diagnostic correlation not guaranteed.']];let art=0;const artEl=document.querySelector('#artifact');artEl.textContent=arts[0][0];document.querySelector('#crank').onclick=()=>{artEl.classList.remove('spin');void artEl.offsetWidth;artEl.classList.add('spin');let next=art;while(next===art)next=Math.floor(Math.random()*arts.length);art=next;setTimeout(()=>{artEl.textContent=arts[art][0];document.querySelector('#caption').textContent=arts[art][1]},250)};document.querySelector('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(phrase());document.querySelector('#copy').textContent='COPIED';setTimeout(()=>document.querySelector('#copy').textContent='COPY PHRASE',1000)}catch{document.querySelector('#copy').textContent='COPY UNAVAILABLE'}};render();